config/routes.rb
# Rails.application.routes.draw do
#   # namespace :workarea do
#     resources :contact_details
#   # end
# end

Workarea::Admin::Engine.routes.draw do
  resources :contact_details
end

Workarea::Storefront::Engine.routes.draw do
  resources :contact_details
end

app/models/workarea/contact_detail.rb
module Workarea
  class ContactDetail
    include ApplicationDocument

    ATTRIBUTES_FOR_LENGTH_VALIDATION = [
      :name,
      :email,
      :comments
    ]

    field :name, type: String
    field :email, type: String
    field :comments, type: String

    # embedded_in :addressable, polymorphic: true
    validates :name, length: { maximum: 30 }
    validates :email, length: { maximum: 50 }
    # ATTRIBUTES_FOR_LENGTH_VALIDATION.each do |field|
    #   validates field, length: { maximum: 500 }
    # end
  end
end

app/controllers/workarea/admin/contact_details.rb
module Workarea
  module Admin
    class ContactDetailsController < Admin::ApplicationController
      required_permissions :marketing
      def index
        @contact_details = Workarea::ContactDetail.all
      end
    end
  end
end

app/controllers/workarea/storefront/contact_details_controller.rb
module Workarea
  module Storefront
    class ContactDetailsController < Storefront::ApplicationController
      # before_action :cache_page
      def new
        @contact_detail = Workarea::ContactDetail.new
      end

      def create
        @contact_detail = Workarea::ContactDetail.new(contact_detail_params)
        if @contact_detail.save
          flash[:success] = 'Blog has been created'
          redirect_to contact_detail_path(@contact_detail)
        else
          render :new
        end
      end

      def index
      end
      # def index
      #   blogs = Workarea::Content::Blog.all.map do |blog|
      #     Storefront::BlogViewModel.new(blog, view_model_options)
      #   end
      #   @blog_index = Storefront::BlogIndexViewModel.new(blogs, view_model_options)
      # end

      # def show
      #   model = Content::Blog.find_by(slug: params[:id])
      #   @blog = Storefront::BlogViewModel.new(model, view_model_options)
      # end

      def contact_detail_params
        return {} if params[:contact_detail].blank?
        params[:contact_detail].permit(:name, :email, :comments)
      end
    end
  end
end

app/helpers/workarea/constact_details_helper.rb
module Workarea::ConstactDetailsHelper
end

app/views/workarea/admin/contact_details/index.html.haml
.grid.grid.grid-container
  - @contact_details.each do |contact_detail|
    .grid__cell.grid__cell--33
      .view__heading
        %b='Name: '
        = contact_detail.name
      .view__heading
        %b='Email: '
        =  contact_detail.email
      .view__heading
        %b='Comment: '
        =  contact_detail.comments
:css
  .grid-container {
    grid-gap: 10px;
    grid-template: 150px;
    background-color: #2196F3;
    padding: 10px;
  }

  .grid-container > div {
    background-color: rgba(255, 255, 255, 0.8);
    text-align: center;
    padding: 20px 0;
    font-size: 30px;
    border: 1px solid;
  }

app/views/workarea/storefront/contact_details/new.html.haml
= form_tag contact_details_path(@contact_detail), method: 'post', data: { unsaved_changes: '' } do
  - if @contact_detail.errors.present?
    - @contact_detail.errors.full_messages.each do |message|
      %li= message

  .view
    .view__header
      .view__heading
        %h1='New Contact Detail'

    .section
      .bulk-actions
        .grid.grid--middle.grid--center
          .grid__cell.grid__cell--50
            .bulk-actions__section
              .bulk-actions__sub-section
                .property
                  = label_tag 'contact_detail[name]', 'Name', class: 'property__name'
                  = text_field_tag 'contact_detail[name]', @contact_detail.name, class: 'text-box'
              .bulk-actions__sub-section
                .property
                  = label_tag 'contact_detail[email]', 'Email', class: 'property__name'
                  = text_field_tag 'contact_detail[email]', @contact_detail.email, class: 'text-box'
              .bulk-actions__sub-section
                .property
                  = label_tag 'contact_detail[comments]', 'Comments', class: 'property__name'
                  = text_area_tag 'contact_detail[comments]', @contact_detail.comments, class: 'text-box', maximum: 300

        .grid__cell.grid__cell--33
          .grid.grid--auto.grid--right.grid--middle
            .grid__cell= button_tag 'Save Contact Detail', value: 'create_contact_detail', class: 'workflow-bar__button workflow-bar__button--update'